### ISSUE TITLE
Project Does not have a License!

### ISSUE THREAD

**Issue by K-Mistele** [amistele/ascii-adventure#14]
Need to upload a license to the repository. A license should...
- Protect our copyright on the project
- Prevent others from distributing our project without permission (and especially not for monetary gain)
- Protect us from damages the project may cause to peoples' computers

**Comment by K-Mistele** [comment]
@Michael-N @amistele

**Comment by K-Mistele** [comment]
So I did some research, it looks like if we don't include a license, then standard copyright laws apply. Thoughts, @Michael-N @amistele  ? Is that enough, or do we want stronger protections? I don't really want this distributed as an open-source project, and I don't think Andrew does either.

**Comment by amistele** [comment]
I really don't care, no one is going to distribute this since there are much better, similar projects available. Standard copyright is fine with me.

**Comment by Michael-N** [comment]
Apple 2.0 license added link: https://opensource.org/licenses/APSL-2.0
