### ISSUE TITLE
Documentation / Wiki

### ISSUE THREAD

**Issue by amistele** [amistele/ascii-adventure#52]
Instead of going in and documenting everything and trying to figure all that out, can we just use the built-in GitHub `Wiki` feature from the main repo toolbar? I have no familiarity with, but it seems as though it's easier to manage and more user-friendly for anyone else who might want to use the repository... thoughts, any familiarity with?

**Comment by K-Mistele** [comment]
@amistele finished documenting world tile characters, mob and entity characters, and controls....
What else? Do we want it to be a user wiki or a programmer wiki?
