### ISSUE TITLE
error on OS X NON ascii character

### ISSUE THREAD

**Issue by rlairson** [amistele/ascii-adventure#53]
Traceback (most recent call last):
  File "adventure.py", line 2, in <module>
    from tile_classes import world_tile
  File "/Users/student/Downloads/seeker-of-the-sword-enhancement-high-scores/tile_classes.py", line 29
SyntaxError: Non-ASCII character '\xe2' in file /Users/student/Downloads/seeker-of-the-sword-enhancement-high-scores/tile_classes.py on line 29, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by amistele** [comment]
Only a problem when trying to run code with previous python versions, just happens to be the first issue encountered.
